version: "3.8"

services:
  controllerdb:
    container_name: controllerdb
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./src/db/init-mongo.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}

  controllerapi:
    container_name: controllerapi
    build: .
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - controllerdb
    ports:
      - ${PORT}:${PORT}